name: Build SunamoDictionary

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoDictionary
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDictionary/SunamoDictionary.csproj

    - name: Build
      run: dotnet build SunamoDictionary/SunamoDictionary.csproj --configuration Release --no-restore

  test:
    name: Test SunamoDictionary.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDictionary.Tests/SunamoDictionary.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoDictionary.Tests/SunamoDictionary.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoDictionary.Tests/SunamoDictionary.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
